// <auto-generated />
using Education_Software.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Education_Software.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230517080239_3")]
    partial class _3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Education_Software.Models.QuestionModel", b =>
                {
                    b.Property<string>("q_id")
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("chapter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("q_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sub_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.HasKey("q_id");

                    b.ToTable("QuestionModel");
                });

            modelBuilder.Entity("Education_Software.Models.SubjectModel", b =>
                {
                    b.Property<string>("sub_id")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("description_reading")
                        .HasColumnType("INT");

                    b.Property<string>("learning_outcomes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("learning_outcomes_reading")
                        .HasColumnType("INT");

                    b.Property<decimal>("semester")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("skills_acquired")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("skills_acquired_reading")
                        .HasColumnType("INT");

                    b.Property<string>("specialization_link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("specialization_link_reading")
                        .HasColumnType("INT");

                    b.Property<string>("sub_type")
                        .IsRequired()
                        .HasColumnType("CHAR");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("sub_id");

                    b.ToTable("SubjectModel");
                });

            modelBuilder.Entity("Education_Software.Models.UserModel", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("student_state")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("username");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
